Feat/#6/kategorieverwaltung
NickLammerskitten/software-engineering pull request #37
Opened 2024-12-13 13:37 UTC by NickLammerskitten

2024-12-13 18:42 UTC, Jaybee18 commented on src/app/(pages)/gallery/page.tsx
> +                        className={"top_action_buttons"}
Die Klasse macht nichts, sollte raus

2024-12-13 19:01 UTC, Jaybee18 commented on src/app/models/category.model.ts
Bitte die andere Datei die hier parallel liegt: "userRole.ts" auch nach diesem schema benennen. Wenn dann einheitlich.

Also zu "user-role.model.ts".
(in kebab-case, weil wir das bei den anderen files auch so schon haben!)

2024-12-13 19:54 UTC, Jaybee18 commented on src/app/api/category/[id]/route.ts
> +            status: 404
Würde sagen das ist eher ein 400

2024-12-13 19:55 UTC, Jaybee18 commented on src/app/api/category/[id]/route.ts
> +            status: 404
Wieder eher ein 400

2024-12-13 20:03 UTC, NickLammerskitten commented on src/app/(pages)/gallery/page.tsx
> +                        className={"top_action_buttons"}
Die macht nen margin top

2024-12-13 20:03 UTC, NickLammerskitten commented on src/app/models/category.model.ts
Erledigt

2024-12-13 20:24 UTC, Jaybee18 commented on src/app/components/add-category-form.tsx
> +            const form = document.getElementById("add-category-form") as HTMLFormElement;
Sollten wir hier ein useRef hook benutzen? Was denkst du?

2024-12-13 20:49 UTC, Jaybee18 commented on src/app/(pages)/gallery/page.tsx
> +                        className={"top_action_buttons"}
Hat bei mir keinen Unterschied im UI gemacht

2024-12-13 20:52 UTC, Jaybee18 commented on src/app/components/add-category-form.tsx
Abbrechen sollte zurück auf die Kategorieliste redirecten.
Speichern redirectet nicht, daher muss es ne andere Möglichkeit geben zurück zu kommen wie n Pfeil oben links.

2024-12-13 22:23 UTC, Jaybee18 commented on src/app/components/category-list.tsx
> +    }
Kategorien können nicht gelöscht werden, wenn sie noch in der image-Tabelle referenziert werden.
Das macht zwar so Sinn, aber dem User wird das nicht angezeigt. 
Vllt sollte man hier vorher einmal separat testen, ob die Kategorie noch verwendet wird, und falls ja, dem User eine Fehlermeldung geben.
Und ansonsten die DELETE request ausführen.

2024-12-13 22:32 UTC, Jaybee18 requested changes
Changes stehen in den Kommentaren

2024-12-14 08:08 UTC, Jaybee18 commented on src/app/components/add-category-form.tsx
> +            const form = document.getElementById("add-category-form") as HTMLFormElement;
useRef wird jetzt benutzt

2024-12-14 08:56 UTC, Jaybee18 commented on src/app/components/add-category-form.tsx
Zurück Button ist implementiert. Abbrechen redirectet auch zurück auf die Kategorienliste

2024-12-14 08:57 UTC, Jaybee18 commented on src/app/components/edit-category-form.tsx
Auch hier sind die fixes von der anderen Seite drin

2024-12-14 10:50 UTC, Jaybee18 commented on src/app/components/category-list.tsx
> +    }
Fehler des Backends wird jetzt im Frontend angezeigt

2024-12-15 12:21 UTC, Jaybee18 approved these changes

2024-12-15 12:22 UTC, merged