Feat/#36/notifications
NickLammerskitten/software-engineering pull request #65
Opened 2024-12-27 09:13 UTC by NickLammerskitten

2024-12-27 14:24 UTC, Jaybee18 commented on src/app/content.tsx
Das kommt in die layout.tsx

2024-12-27 14:25 UTC, Jaybee18 requested changes
angemerkte changes

2024-12-28 11:27 UTC, NickLammerskitten commented on src/app/content.tsx
Das geht nicht, da der Snackbar provider in einer Client Component muss. Daher habe ich eine Content component geschrieben, die explizit nur den Content inne hat und den Snackbar Provider drum herum

2024-12-28 15:53 UTC, Jaybee18 commented on src/app/content.tsx
ja gut ist nicht schön, aber funktioniert

2024-12-28 15:54 UTC, Jaybee18 approved these changes

2024-12-29 19:05 UTC, merged